[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "src"
script = "script"
solc = "0.8.24"
isolate = true
fs_permissions = [{ access = "read", path = "./"}]

[fmt]
tab_width = 2
bracket_spacing = true
sort_imports = true
